version: '3'
services:
  php:
    build:
      context: ./docker/php
    volumes:
      - ./src/:/var/www/html
    links:
      - "mysql"
      - "nginx"

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./src/:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d

  mysql:
    build:
      context: ./docker/data
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
